### ISSUE TITLE
Recordings count doesn't match number of rows returned

### ISSUE THREAD

**Issue by arthurmcgregor** [TheCacophonyProject/cacophony-api#116] opened 2018-07-04 23:29 UTC
I discovered this when playing around with visualising the number of recordings per device.

For the following query: {type: "thermalRaw", DeviceId: "373"}
To this URL: https://api-test.cacophony.org.nz/api/v1/recordings

When I first call the API with limit = 100, it returns 100 rows of recordings and a count of 2402
When I call the API again with limit = 2402, it returns 2322 rows ie 80 rows are missing.

![missing rows](https://user-images.githubusercontent.com/24260476/42296118-c95550f4-8045-11e8-96cd-19c1ab4742a4.png)

I hunted around with different dates and found this situation - clearly a count of 3 but only 2 rows showing:
![missing row](https://user-images.githubusercontent.com/24260476/42296176-a50f7944-8046-11e8-9f99-2755a080e5eb.png)

**Comment by mjs** [comment] 2019-07-25 04:50
Duplicate of #173.

**Closed by mjs** 2019-07-25 04:50 UTC
Labels: bug, duplicate
